[build]
command = "curl -sL https://storage.googleapis.com/download.flutter.io/flutter_linux_v1.12.13+hotfix.9-stable.tar.xz | tar xJf - && export PATH=$(pwd)/flutter/bin:$PATH && flutter doctor && flutter build web"
publish = "build/web"
